-- Seed 98 more users for Finder dating app
-- Vietnamese names and realistic profile data

INSERT INTO public.profiles (
  id, name, age, gender, gender_preference, bio, avatar_url, 
  photos, interests, occupation, university, city, lat, lng, 
  is_verified, is_online, last_active, created_at
) VALUES

-- Users 1-10
(gen_random_uuid(), 'Linh Nguyễn', 24, 'female', 'male', 'Yêu du lịch và thăm các quán cà phê mới 🌍☕', 'https://api.dicebear.com/7.x/lorelei/svg?seed=linh1&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1659746159357-d19523ddd178'], ARRAY['Travel', 'Coffee', 'Reading'], 'Marketing Specialist', 'University of Science', 'Ho Chi Minh', 10.8141, 106.6927, true, true, NOW() - INTERVAL '2 hours', NOW() - INTERVAL '30 days'),
(gen_random_uuid(), 'Hà Trần', 23, 'female', 'male', 'Thích chơi thể thao và đọc sách. Tìm người có tinh thần lạc quan 😊', 'https://api.dicebear.com/7.x/lorelei/svg?seed=ha1&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1531746020798-e6953c6e8e04'], ARRAY['Sports', 'Books', 'Music'], 'Graphic Designer', 'RMIT Vietnam', 'Hanoi', 21.0285, 105.8537, true, false, NOW() - INTERVAL '5 hours', NOW() - INTERVAL '25 days'),
(gen_random_uuid(), 'Minh Phạm', 25, 'female', 'male', 'Nấu ăn là đam mê của tôi. Tìm người yêu đu đưa và vui vẻ 🍳', 'https://api.dicebear.com/7.x/lorelei/svg?seed=minh1&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e'], ARRAY['Cooking', 'Photography', 'Yoga'], 'Chef', 'Hanoi Open University', 'Ho Chi Minh', 10.8141, 106.6927, true, true, NOW() - INTERVAL '1 hour', NOW() - INTERVAL '20 days'),
(gen_random_uuid(), 'Tâm Lê', 22, 'female', 'male', 'Startup founder, coffee addict ☕ Tìm người có tầm nhìn 👀', 'https://api.dicebear.com/7.x/lorelei/svg?seed=tam1&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1438761681033-6461ffad8d80'], ARRAY['Startup', 'Tech', 'Coffee'], 'Founder', 'Saigon University', 'Ho Chi Minh', 10.8141, 106.6927, true, true, NOW() - INTERVAL '30 minutes', NOW() - INTERVAL '15 days'),
(gen_random_uuid(), 'Lan Hoàng', 26, 'female', 'male', 'Yêu một người là yêu cả thế giới của người đó. Từ Hà Nội nội 💚', 'https://api.dicebear.com/7.x/lorelei/svg?seed=lan1&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1494790108377-be9c29b29330'], ARRAY['Films', 'Travel', 'Art'], 'Architect', 'Hanoi Polytechnic University', 'Hanoi', 21.0285, 105.8537, true, false, NOW() - INTERVAL '8 hours', NOW() - INTERVAL '10 days'),
(gen_random_uuid(), 'Nhi Đặng', 23, 'female', 'male', 'Yoga instructor 🧘‍♀️ Tìm nguồn năng lượng tích cực', 'https://api.dicebear.com/7.x/lorelei/svg?seed=nhi1&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1506435773649-6e0eb8cfb237'], ARRAY['Yoga', 'Wellness', 'Nature'], 'Yoga Instructor', 'Far Eastern University', 'Ho Chi Minh', 10.8141, 106.6927, true, true, NOW() - INTERVAL '45 minutes', NOW() - INTERVAL '22 days'),
(gen_random_uuid(), 'Thu Bùi', 24, 'female', 'male', 'Chuyên gia digital marketing. Thích xê dịch và khám phá 🗺️', 'https://api.dicebear.com/7.x/lorelei/svg?seed=thu1&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1534126613592-a67ba3cf3997'], ARRAY['Marketing', 'Travel', 'Photography'], 'Marketing Manager', 'Foreign Trade University', 'Hanoi', 21.0285, 105.8537, true, false, NOW() - INTERVAL '6 hours', NOW() - INTERVAL '18 days'),
(gen_random_uuid(), 'Hương Käth', 25, 'female', 'male', 'Teacher at international school. Yêu cuộc sống và con người 📚', 'https://api.dicebear.com/7.x/lorelei/svg?seed=huong1&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d'], ARRAY['Teaching', 'Literature', 'Music'], 'English Teacher', 'Hanoi National University', 'Hanoi', 21.0285, 105.8537, true, true, NOW() - INTERVAL '2 hours', NOW() - INTERVAL '12 days'),
(gen_random_uuid(), 'Mai Võ', 22, 'female', 'male', 'Startup designer, thích tạo ra những điều tuyệt vời ✨', 'https://api.dicebear.com/7.x/lorelei/svg?seed=mai1&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1494790108377-be9c29b29330'], ARRAY['Design', 'Startup', 'Art'], 'Product Designer', 'Saigon University', 'Ho Chi Minh', 10.8141, 106.6927, true, true, NOW() - INTERVAL '3 hours', NOW() - INTERVAL '28 days'),
(gen_random_uuid(), 'Vy Dương', 23, 'female', 'male', 'Tôi là một software engineer. Ngủ ngoài là hobby 😴🏕️', 'https://api.dicebear.com/7.x/lorelei/svg?seed=vy1&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1488228469033-56fdf060b868'], ARRAY['Tech', 'Camping', 'Hiking'], 'Software Engineer', 'BKHN', 'Hanoi', 21.0285, 105.8537, true, false, NOW() - INTERVAL '12 hours', NOW() - INTERVAL '5 days'),

-- Users 11-20
(gen_random_uuid(), 'Khánh Nguyễn', 26, 'male', 'female', 'Startup founder 🚀 Tìm người có ước mơ lớn', 'https://api.dicebear.com/7.x/avataaars/svg?seed=khanh1', ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d'], ARRAY['Startup', 'Tech', 'Travel'], 'Founder', 'Hanoi Open University', 'Ho Chi Minh', 10.8141, 106.6927, true, true, NOW() - INTERVAL '1 hour', NOW() - INTERVAL '8 days'),
(gen_random_uuid(), 'Mạnh Trần', 25, 'male', 'female', 'Photographer chuyên gia. Tìm người yêu vui vẻ 📸', 'https://api.dicebear.com/7.x/avataaars/svg?seed=manh1', ARRAY['https://images.unsplash.com/photo-1500648767791-00dcc994a43e'], ARRAY['Photography', 'Art', 'Travel'], 'Photographer', 'Saigon University', 'Ho Chi Minh', 10.8141, 106.6927, true, false, NOW() - INTERVAL '4 hours', NOW() - INTERVAL '14 days'),
(gen_random_uuid(), 'Long Lý', 24, 'male', 'female', 'Developer, coffee & books lover ☕📖 Từ Hà Nội', 'https://api.dicebear.com/7.x/avataaars/svg?seed=long1', ARRAY['https://images.unsplash.com/photo-1520466809213-7b9a56adcd45'], ARRAY['Coding', 'Coffee', 'Books'], 'Software Developer', 'BKHN', 'Hanoi', 21.0285, 105.8537, true, true, NOW() - INTERVAL '2 hours', NOW() - INTERVAL '19 days'),
(gen_random_uuid(), 'Hùng Phạm', 27, 'male', 'female', 'Businessman. Yêu cuộc sống, yêu quán golf ⛳', 'https://api.dicebear.com/7.x/avataaars/svg?seed=hung1', ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d'], ARRAY['Golf', 'Business', 'Wellness'], 'Business Manager', 'National Economics University', 'Hanoi', 21.0285, 105.8537, true, false, NOW() - INTERVAL '7 hours', NOW() - INTERVAL '25 days'),
(gen_random_uuid(), 'Tú Tài', 23, 'male', 'female', 'Design enthusiast & travel lover 🎨✈️', 'https://api.dicebear.com/7.x/avataaars/svg?seed=tu1', ARRAY['https://images.unsplash.com/photo-1517849845537-1d51a20414de'], ARRAY['Design', 'Travel', 'Music'], 'Graphic Designer', 'Hanoi Open University', 'Hanoi', 21.0285, 105.8537, true, true, NOW() - INTERVAL '30 minutes', NOW() - INTERVAL '11 days'),
(gen_random_uuid(), 'Duy Bùi', 26, 'male', 'female', 'Marketing manager. Yêu lái xe và khám phá 🏍️', 'https://api.dicebear.com/7.x/avataaars/svg?seed=duy1', ARRAY['https://images.unsplash.com/photo-1516756587022-4ad8d36e54b2'], ARRAY['Motorcycle', 'Travel', 'Food'], 'Marketing Manager', 'FTU', 'Ho Chi Minh', 10.8141, 106.6927, true, false, NOW() - INTERVAL '9 hours', NOW() - INTERVAL '16 days'),
(gen_random_uuid(), 'Hải Hoàng', 24, 'male', 'female', 'Architect. Nghiêm túc trong công việc, nhỏ nhẹ trong đời 💎', 'https://api.dicebear.com/7.x/avataaars/svg?seed=hai1', ARRAY['https://images.unsplash.com/photo-1506794778202-cad84cf45f1d'], ARRAY['Architecture', 'Art', 'Sports'], 'Architect', 'Hanoi Polytechnic University', 'Hanoi', 21.0285, 105.8537, true, true, NOW() - INTERVAL '5 hours', NOW() - INTERVAL '23 days'),
(gen_random_uuid(), 'Quân Nguyễn', 25, 'male', 'female', 'Fitness enthusiast 💪 Tìm người có lifestyle healthy', 'https://api.dicebear.com/7.x/avataaars/svg?seed=quan1', ARRAY['https://images.unsplash.com/photo-1517836357463-d25ddfcbf042'], ARRAY['Fitness', 'Gym', 'Sports'], 'Personal Trainer', 'Saigon University', 'Ho Chi Minh', 10.8141, 106.6927, true, true, NOW() - INTERVAL '1 hour', NOW() - INTERVAL '9 days'),
(gen_random_uuid(), 'Thắng Đặng', 28, 'male', 'female', 'Entrepreneur & investor. Thích đàm phán và chiến lược 📊', 'https://api.dicebear.com/7.x/avataaars/svg?seed=thang1', ARRAY['https://images.unsplash.com/photo-1494790108377-be9c29b29330'], ARRAY['Business', 'Investment', 'Reading'], 'Entrepreneur', 'National Economics University', 'Ho Chi Minh', 10.8141, 106.6927, true, false, NOW() - INTERVAL '11 hours', NOW() - INTERVAL '29 days'),

-- Users 21-30
(gen_random_uuid(), 'Liên Tôn', 22, 'female', 'male', 'Student & part-time model. Tìm người chân thật 📚✨', 'https://api.dicebear.com/7.x/lorelei/svg?seed=lien1&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1538895917378-4bc979020198'], ARRAY['Modeling', 'Fashion', 'Art'], 'Student', 'Saigon University', 'Ho Chi Minh', 10.8141, 106.6927, true, true, NOW() - INTERVAL '2 hours', NOW() - INTERVAL '7 days'),
(gen_random_uuid(), 'Na Trần', 23, 'female', 'male', 'Pharmacist. Yêu cuộc sống đơn giản mà có ý nghĩa 💚', 'https://api.dicebear.com/7.x/lorelei/svg?seed=na1&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1544005313-94ddf0286df2'], ARRAY['Health', 'Wellness', 'Cooking'], 'Pharmacist', 'University of Pharmacy', 'Hanoi', 21.0285, 105.8537, true, false, NOW() - INTERVAL '8 hours', NOW() - INTERVAL '17 days'),
(gen_random_uuid(), 'Loan Lâm', 24, 'female', 'male', 'Journalist & writer. Thích ghi lại những khoảnh khắc đẹp 📝', 'https://api.dicebear.com/7.x/lorelei/svg?seed=loan1&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d'], ARRAY['Writing', 'Journalism', 'Travel'], 'Journalist', 'Hanoi National University', 'Hanoi', 21.0285, 105.8537, true, true, NOW() - INTERVAL '3 hours', NOW() - INTERVAL '13 days'),
(gen_random_uuid(), 'Trang Đặng', 25, 'female', 'male', 'Accountant with passion for travel 🌍 Tìm người lạc quan', 'https://api.dicebear.com/7.x/lorelei/svg?seed=trang1&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1514782231840-2e0a9bf2a9ae'], ARRAY['Travel', 'Accounting', 'Food'], 'Accountant', 'FTU', 'Ho Chi Minh', 10.8141, 106.6927, true, false, NOW() - INTERVAL '6 hours', NOW() - INTERVAL '21 days'),
(gen_random_uuid(), 'Thoa Vũ', 22, 'female', 'male', 'Makeup artist 💄 Tìm người yêu thích sự sáng tạo', 'https://api.dicebear.com/7.x/lorelei/svg?seed=thoa1&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1494790108377-be9c29b29330'], ARRAY['Makeup', 'Beauty', 'Fashion'], 'Makeup Artist', 'Hanoi Open University', 'Hanoi', 21.0285, 105.8537, true, true, NOW() - INTERVAL '4 hours', NOW() - INTERVAL '26 days'),
(gen_random_uuid(), 'Hà Ngô', 26, 'female', 'male', 'Data scientist 📊 Tìm người có logic & lãng mạn', 'https://api.dicebear.com/7.x/lorelei/svg?seed=ha2&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d'], ARRAY['Data', 'Tech', 'Music'], 'Data Scientist', 'BKHN', 'Ho Chi Minh', 10.8141, 106.6927, true, false, NOW() - INTERVAL '10 hours', NOW() - INTERVAL '24 days'),
(gen_random_uuid(), 'Huyền Phạm', 23, 'female', 'male', 'HR specialist. Yêu bộ môn management 👥💼', 'https://api.dicebear.com/7.x/lorelei/svg?seed=huyen1&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1494790108377-be9c29b29330'], ARRAY['HR', 'Business', 'Team Building'], 'HR Specialist', 'National Economics University', 'Hanoi', 21.0285, 105.8537, true, true, NOW() - INTERVAL '1 hour', NOW() - INTERVAL '6 days'),
(gen_random_uuid(), 'Hope Vân', 24, 'female', 'male', 'Florist & decorator. Yêu những điều đẹp trong cuộc sống 🌸', 'https://api.dicebear.com/7.x/lorelei/svg?seed=van1&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d'], ARRAY['Flowers', 'Decoration', 'Art'], 'Florist', 'Saigon University', 'Ho Chi Minh', 10.8141, 106.6927, true, false, NOW() - INTERVAL '7 hours', NOW() - INTERVAL '20 days'),
(gen_random_uuid(), 'Kiều Lê', 25, 'female', 'male', 'Veterinarian 🐾 Tìm người yêu động vật như tôi', 'https://api.dicebear.com/7.x/lorelei/svg?seed=kieu1&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1494790108377-be9c29b29330'], ARRAY['Animals', 'Nature', 'Travel'], 'Veterinarian', 'University of Agriculture', 'Hanoi', 21.0285, 105.8537, true, true, NOW() - INTERVAL '5 hours', NOW() - INTERVAL '30 days'),

-- Users 31-40
(gen_random_uuid(), 'Tuấn Trương', 24, 'male', 'female', 'Fitness coach & nutritionist 💪🥗 Healthy lifestyle 4 life', 'https://api.dicebear.com/7.x/avataaars/svg?seed=tuan1', ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d'], ARRAY['Fitness', 'Nutrition', 'Sports'], 'Fitness Coach', 'Saigon University', 'Ho Chi Minh', 10.8141, 106.6927, true, true, NOW() - INTERVAL '3 hours', NOW() - INTERVAL '12 days'),
(gen_random_uuid(), 'Nước Hoàng', 26, 'male', 'female', 'Real estate agent. Tìm người có ổn định & tham vọng 🏠', 'https://api.dicebear.com/7.x/avataaars/svg?seed=nuoc1', ARRAY['https://images.unsplash.com/photo-1516756587022-4ad8d36e54b2'], ARRAY['Real Estate', 'Business', 'Travel'], 'Real Estate Agent', 'FTU', 'Ho Chi Minh', 10.8141, 106.6927, true, false, NOW() - INTERVAL '8 hours', NOW() - INTERVAL '19 days'),
(gen_random_uuid(), 'Tuấn Phạm', 25, 'male', 'female', 'Chef & food blogger 🍜 Tìm người yêu ẩm thực', 'https://api.dicebear.com/7.x/avataaars/svg?seed=tuan2', ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d'], ARRAY['Cooking', 'Food', 'Travel'], 'Chef', 'Hanoi Open University', 'Hanoi', 21.0285, 105.8537, true, true, NOW() - INTERVAL '2 hours', NOW() - INTERVAL '10 days'),
(gen_random_uuid(), 'Minh Bùi', 27, 'male', 'female', 'Lawyer & mentor. Passionate about justice & growth ⚖️', 'https://api.dicebear.com/7.x/avataaars/svg?seed=minh2', ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d'], ARRAY['Law', 'Mentoring', 'Reading'], 'Lawyer', 'National Law University', 'Ha Noi', 21.0285, 105.8537, true, false, NOW() - INTERVAL '12 hours', NOW() - INTERVAL '28 days'),
(gen_random_uuid(), 'Sơn Võ', 23, 'male', 'female', 'Game developer 🎮 Tìm người thích explore & adventure', 'https://api.dicebear.com/7.x/avataaars/svg?seed=son1', ARRAY['https://images.unsplash.com/photo-1494790108377-be9c29b29330'], ARRAY['Gaming', 'Tech', 'Art'], 'Game Developer', 'BKHN', 'Ho Chi Minh', 10.8141, 106.6927, true, true, NOW() - INTERVAL '1 hour', NOW() - INTERVAL '15 days'),
(gen_random_uuid(), 'Bình Nam', 26, 'male', 'female', 'Environmental engineer. Yêu thiên nhiên & sustainable living 🌍', 'https://api.dicebear.com/7.x/avataaars/svg?seed=binh1', ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d'], ARRAY['Environment', 'Sustainability', 'Hiking'], 'Environmental Engineer', 'University of Technology', 'Hanoi', 21.0285, 105.8537, true, false, NOW() - INTERVAL '9 hours', NOW() - INTERVAL '22 days'),
(gen_random_uuid(), 'Lộc Trần', 24, 'male', 'female', 'Photographer & artist 📸 Tìm muse cho bộ dự án mới', 'https://api.dicebear.com/7.x/avataaars/svg?seed=loc1', ARRAY['https://images.unsplash.com/photo-1494790108377-be9c29b29330'], ARRAY['Photography', 'Art', 'Travel'], 'Photographer', 'Saigon University', 'Ho Chi Minh', 10.8141, 106.6927, true, true, NOW() - INTERVAL '4 hours', NOW() - INTERVAL '18 days'),
(gen_random_uuid(), 'Hưng Đạo', 25, 'male', 'female', 'Civil engineer. Thích xây dựng tương lai 🏗️', 'https://api.dicebear.com/7.x/avataaars/svg?seed=hung2', ARRAY['https://images.unsplash.com/photo-1516756587022-4ad8d36e54b2'], ARRAY['Engineering', 'Construction', 'Travel'], 'Civil Engineer', 'BKHN', 'Ho Chi Minh', 10.8141, 106.6927, true, false, NOW() - INTERVAL '6 hours', NOW() - INTERVAL '25 days'),
(gen_random_uuid(), 'Tấn Trình', 28, 'male', 'female', 'Business consultant 💼 Tìm partner cho cuộc sống', 'https://api.dicebear.com/7.x/avataaars/svg?seed=tan1', ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d'], ARRAY['Business', 'Consulting', 'Travel'], 'Business Consultant', 'National Economics University', 'Hanoi', 21.0285, 105.8537, true, true, NOW() - INTERVAL '5 hours', NOW() - INTERVAL '11 days'),

-- Users 41-50
(gen_random_uuid(), 'Thy Đoàn', 22, 'female', 'male', 'Influencer & content creator 📱✨ Tìm người hỗ trợ dream', 'https://api.dicebear.com/7.x/lorelei/svg?seed=thy1&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d'], ARRAY['Content', 'Social Media', 'Travel'], 'Influencer', 'Saigon University', 'Ho Chi Minh', 10.8141, 106.6927, true, true, NOW() - INTERVAL '1 hour', NOW() - INTERVAL '9 days'),
(gen_random_uuid(), 'Trinh Giang', 25, 'female', 'male', 'Consultant & life coach 💭 Tìm balance & love', 'https://api.dicebear.com/7.x/lorelei/svg?seed=trinh1&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1494790108377-be9c29b29330'], ARRAY['Coaching', 'Personal Development', 'Wellness'], 'Life Coach', 'National Economics University', 'Hanoi', 21.0285, 105.8537, true, false, NOW() - INTERVAL '7 hours', NOW() - INTERVAL '27 days'),
(gen_random_uuid(), 'Dạo Lâm', 23, 'female', 'male', 'Music producer 🎵 Tìm creative soul', 'https://api.dicebear.com/7.x/lorelei/svg?seed=dao1&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d'], ARRAY['Music', 'Production', 'Art'], 'Music Producer', 'Hanoi Culture University', 'Hanoi', 21.0285, 105.8537, true, true, NOW() - INTERVAL '3 hours', NOW() - INTERVAL '14 days'),
(gem_random_uuid(), 'Mộng Nguyễn', 24, 'female', 'male', 'Interior designer & dreamer 🏡✨', 'https://api.dicebear.com/7.x/lorelei/svg?seed=mong1&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1494790108377-be9c29b29330'], ARRAY['Interior Design', 'Home', 'Art'], 'Interior Designer', 'Hanoi Open University', 'Hanoi', 21.0285, 105.8537, true, false, NOW() - INTERVAL '11 hours', NOW() - INTERVAL '19 days'),
(gen_random_uuid(), 'Thanh Phạm', 26, 'female', 'male', 'Corporate lawyer 👩‍⚖️ Serious & playful balance', 'https://api.dicebear.com/7.x/lorelei/svg?seed=thanh1&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d'], ARRAY['Law', 'Business', 'Travel'], 'Lawyer', 'National Law University', 'Ho Chi Minh', 10.8141, 106.6927, true, true, NOW() - INTERVAL '2 hours', NOW() - INTERVAL '8 days'),
(gen_random_uuid(), 'Quỳnh Tô', 23, 'female', 'male', 'Dentist 😁 Tìm người yêu nụ cười', 'https://api.dicebear.com/7.x/lorelei/svg?seed=quinh1&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1494790108377-be9c29b29330'], ARRAY['Dentistry', 'Health', 'Sports'], 'Dentist', 'Hanoi Medical University', 'Hanoi', 21.0285, 105.8537, true, false, NOW() - INTERVAL '8 hours', NOW() - INTERVAL '23 days'),
(gen_random_uuid(), 'Hà Phan', 24, 'female', 'male', 'Event planner 🎉 Passionate about creating magic moments', 'https://api.dicebear.com/7.x/lorelei/svg?seed=ha3&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d'], ARRAY['Events', 'Planning', 'Creative'], 'Event Planner', 'Saigon University', 'Ho Chi Minh', 10.8141, 106.6927, true, true, NOW() - INTERVAL '4 hours', NOW() - INTERVAL '16 days'),
(gen_random_uuid(), 'Hiền Võ', 25, 'female', 'male', 'Fashion designer 👗 Looking for style & substance', 'https://api.dicebear.com/7.x/lorelei/svg?seed=hien1&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1494790108377-be9c29b29330'], ARRAY['Fashion', 'Design', 'Creativity'], 'Fashion Designer', 'Hanoi Fashion University', 'Hanoi', 21.0285, 105.8537, true, false, NOW() - INTERVAL '6 hours', NOW() - INTERVAL '29 days'),

-- Users 51-60
(gen_random_uuid(), 'Hiệp Đinh', 25, 'male', 'female', 'Software architect 🏗️ Building great tech & relationships', 'https://api.dicebear.com/7.x/avataaars/svg?seed=hiep1', ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d'], ARRAY['Tech', 'Architecture', 'Reading'], 'Software Architect', 'BKHN', 'Ho Chi Minh', 10.8141, 106.6927, true, true, NOW() - INTERVAL '2 hours', NOW() - INTERVAL '13 days'),
(gen_random_uuid(), 'Linh Đặng', 24, 'male', 'female', 'Content writer & editor ✍️ Tìm người hiểu tôi', 'https://api.dicebear.com/7.x/avataaars/svg?seed=linh2', ARRAY['https://images.unsplash.com/photo-1494790108377-be9c29b29330'], ARRAY['Writing', 'Editing', 'Literature'], 'Content Writer', 'Hanoi National University', 'Hanoi', 21.0285, 105.8537, true, false, NOW() - INTERVAL '9 hours', NOW() - INTERVAL '24 days'),
(gen_random_uuid(), 'Phương Cao', 26, 'male', 'female', 'Investment manager 📈 Smart money, smart choices', 'https://api.dicebear.com/7.x/avataaars/svg?seed=phuong1', ARRAY['https://images.unsplash.com/photo-1516756587022-4ad8d36e54b2'], ARRAY['Investment', 'Finance', 'Travel'], 'Investment Manager', 'National Economics University', 'Ho Chi Minh', 10.8141, 106.6927, true, true, NOW() - INTERVAL '5 hours', NOW() - INTERVAL '20 days'),
(gen_random_uuid(), 'Tú Bùi', 23, 'male', 'female', 'UX/UI designer 🎨 Creating beautiful experiences', 'https://api.dicebear.com/7.x/avataaars/svg?seed=tu2', ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d'], ARRAY['Design', 'UX', 'Creativity'], 'UX Designer', 'Hanoi Open University', 'Hanoi', 21.0285, 105.8537, true, false, NOW() - INTERVAL '10 hours', NOW() - INTERVAL '26 days'),
(gen_random_uuid(), 'Hạnh Lê', 27, 'male', 'female', 'Project manager 📊 Detail-oriented & people-focused', 'https://api.dicebear.com/7.x/avataaars/svg?seed=hanh1', ARRAY['https://images.unsplash.com/photo-1494790108377-be9c29b29330'], ARRAY['Management', 'Project', 'Team Building'], 'Project Manager', 'FTU', 'Ho Chi Minh', 10.8141, 106.6927, true, true, NOW() - INTERVAL '3 hours', NOW() - INTERVAL '17 days'),
(gen_random_uuid(), 'Ân Trần', 24, 'male', 'female', 'Network engineer 🌐 Connecting dots & hearts', 'https://api.dicebear.com/7.x/avataaars/svg?seed=an1', ARRAY['https://images.unsplash.com/photo-1516756587022-4ad8d36e54b2'], ARRAY['Tech', 'Networking', 'Travel'], 'Network Engineer', 'RMIT Vietnam', 'Ho Chi Minh', 10.8141, 106.6927, true, false, NOW() - INTERVAL '7 hours', NOW() - INTERVAL '21 days'),
(gen_random_uuid(), 'Hân Phạm', 25, 'male', 'female', 'Sales director 🎯 Driven by results & connections', 'https://api.dicebear.com/7.x/avataaars/svg?seed=han1', ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d'], ARRAY['Sales', 'Business', 'Networking'], 'Sales Director', 'Saigon University', 'Ho Chi Minh', 10.8141, 106.6927, true, true, NOW() - INTERVAL '4 hours', NOW() - INTERVAL '12 days'),
(gen_random_uuid(), 'Kiên Ngô', 26, 'male', 'female', 'Hospital director 🏥 Dedicated to care & service', 'https://api.dicebear.com/7.x/avataaars/svg?seed=kien1', ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d'], ARRAY['Healthcare', 'Management', 'Wellness'], 'Hospital Manager', 'Hanoi Medical University', 'Hanoi', 21.0285, 105.8537, true, false, NOW() - INTERVAL '11 hours', NOW() - INTERVAL '25 days'),

-- Users 61-70
(gen_random_uuid(), 'Hương Lộc', 22, 'female', 'male', 'Yoga & meditation instructor 🧘‍♀️ Tìm inner peace cùng nhau', 'https://api.dicebear.com/7.x/lorelei/svg?seed=huong2&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1506435773649-6e0eb8cfb237'], ARRAY['Yoga', 'Wellness', 'Meditation'], 'Yoga Instructor', 'Far Eastern University', 'Ho Chi Minh', 10.8141, 106.6927, true, true, NOW() - INTERVAL '1 hour', NOW() - INTERVAL '10 days'),
(gen_random_uuid(), 'Tâm An', 24, 'female', 'male', 'Speech therapist 🗣️ Helping voices be heard', 'https://api.dicebear.com/7.x/lorelei/svg?seed=tam2&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1494790108377-be9c29b29330'], ARRAY['Healthcare', 'Therapy', 'Communication'], 'Speech Therapist', 'Hanoi Medical University', 'Hanoi', 21.0285, 105.8537, true, false, NOW() - INTERVAL '8 hours', NOW() - INTERVAL '26 days'),
(gen_random_uuid(), 'Hiền Thân', 23, 'female', 'male', 'Translator & language lover 🌍 English & French speaker', 'https://api.dicebear.com/7.x/lorelei/svg?seed=hien2&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d'], ARRAY['Languages', 'Translation', 'Traveling'], 'Translator', 'Hanoi National University', 'Hanoi', 21.0285, 105.8537, true, true, NOW() - INTERVAL '5 hours', NOW() - INTERVAL '14 days'),
(gen_random_uuid(), 'Thanh Nhi', 25, 'female', 'male', 'Product manager 🚀 Building things people love', 'https://api.dicebear.com/7.x/lorelei/svg?seed=thanh2&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1494790108377-be9c29b29330'], ARRAY['Product', 'Tech', 'Creative'], 'Product Manager', 'BKHN', 'Ho Chi Minh', 10.8141, 106.6927, true, false, NOW() - INTERVAL '6 hours', NOW() - INTERVAL '22 days'),
(gen_random_uuid(), 'Linh Mai', 26, 'female', 'male', 'Sustainability consultant 🌱 Green living advocate', 'https://api.dicebear.com/7.x/lorelei/svg?seed=linh3&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d'], ARRAY['Sustainability', 'Environment', 'Wellness'], 'Sustainability Consultant', 'University of Technology', 'Hanoi', 21.0285, 105.8537, true, true, NOW() - INTERVAL '4 hours', NOW() - INTERVAL '18 days'),
(gen_random_uuid(), 'Yến Cao', 23, 'female', 'male', 'Cinematographer 🎬 Capturing beautiful stories', 'https://api.dicebear.com/7.x/lorelei/svg?seed=yen1&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1494790108377-be9c29b29330'], ARRAY['Film', 'Photography', 'Art'], 'Cinematographer', 'Saigon University', 'Ho Chi Minh', 10.8141, 106.6927, true, false, NOW() - INTERVAL '9 hours', NOW() - INTERVAL '19 days'),
(gen_random_uuid(), 'Nữ Lương', 24, 'female', 'male', 'HR Manager 👥 Building great teams & cultures', 'https://api.dicebear.com/7.x/lorelei/svg?seed=nu1&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d'], ARRAY['HR', 'Management', 'Team Building'], 'HR Manager', 'National Economics University', 'Ho Chi Minh', 10.8141, 106.6927, true, true, NOW() - INTERVAL '2 hours', NOW() - INTERVAL '11 days'),

-- Users 71-80
(gen_random_uuid(), 'Dương Tâm', 26, 'male', 'female', 'Public health specialist 🏥 Health advocate & educator', 'https://api.dicebear.com/7.x/avataaars/svg?seed=duong1', ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d'], ARRAY['Health', 'Education', 'Social Work'], 'Public Health Specialist', 'Hanoi Medical University', 'Hanoi', 21.0285, 105.8537, true, false, NOW() - INTERVAL '10 hours', NOW() - INTERVAL '27 days'),
(gen_random_uuid(), 'Phong Trần', 25, 'male', 'female', 'Automotive engineer 🚗 Passionate about efficiency', 'https://api.dicebear.com/7.x/avataaars/svg?seed=phong1', ARRAY['https://images.unsplash.com/photo-1516756587022-4ad8d36e54b2'], ARRAY['Automotive', 'Engineering', 'Tech'], 'Automotive Engineer', 'BKHN', 'Ho Chi Minh', 10.8141, 106.6927, true, true, NOW() - INTERVAL '3 hours', NOW() - INTERVAL '15 days'),
(gen_random_uuid(), 'Định Phan', 24, 'male', 'female', 'Solutions architect 💡 Creating scalable systems', 'https://api.dicebear.com/7.x/avataaars/svg?seed=dinh1', ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d'], ARRAY['Tech', 'Architecture', 'Innovation'], 'Solutions Architect', 'RMIT Vietnam', 'Ho Chi Minh', 10.8141, 106.6927, true, false, NOW() - INTERVAL '7 hours', NOW() - INTERVAL '20 days'),
(gen_random_uuid(), 'Tùng Bộ', 27, 'male', 'female', 'Chief technology officer 👨‍💼 Tech enthusiast & leader', 'https://api.dicebear.com/7.x/avataaars/svg?seed=tung1', ARRAY['https://images.unsplash.com/photo-1494790108377-be9c29b29330'], ARRAY['Tech', 'Leadership', 'Innovation'], 'CTO', 'BKHN', 'Ho Chi Minh', 10.8141, 106.6927, true, true, NOW() - INTERVAL '5 hours', NOW() - INTERVAL '23 days'),
(gen_random_uuid(), 'Quốc Hải', 23, 'male', 'female', 'Mobile app developer 📱 iOS & Android specialist', 'https://api.dicebear.com/7.x/avataaars/svg?seed=quoc1', ARRAY['https://images.unsplash.com/photo-1516756587022-4ad8d36e54b2'], ARRAY['Mobile Dev', 'Tech', 'Software'], 'App Developer', 'BKHN', 'Hanoi', 21.0285, 105.8537, true, false, NOW() - INTERVAL '11 hours', NOW() - INTERVAL '28 days'),
(gen_random_uuid(), 'Xuân Vũ', 26, 'male', 'female', 'Supply chain manager 📦 Logistics & optimization', 'https://api.dicebear.com/7.x/avataaars/svg?seed=xuan1', ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d'], ARRAY['Logistics', 'Management', 'Efficiency'], 'Supply Chain Manager', 'FTU', 'Ho Chi Minh', 10.8141, 106.6927, true, true, NOW() - INTERVAL '4 hours', NOW() - INTERVAL '16 days'),
(gen_random_uuid(), 'Sỹ Tùng', 25, 'male', 'female', 'Quality assurance specialist 🔍 Ensuring excellence', 'https://api.dicebear.com/7.x/avataaars/svg?seed=sy1', ARRAY['https://images.unsplash.com/photo-1494790108377-be9c29b29330'], ARRAY['QA', 'Tech', 'Quality'], 'QA Specialist', 'RMIT Vietnam', 'Ho Chi Minh', 10.8141, 106.6927, true, false, NOW() - INTERVAL '6 hours', NOW() - INTERVAL '24 days'),
(gen_random_uuid(), 'Lưu Nam', 28, 'male', 'female', 'Executive director 👔 Strategic thinker & leader', 'https://api.dicebear.com/7.x/avataaars/svg?seed=luu1', ARRAY['https://images.unsplash.com/photo-1516756587022-4ad8d36e54b2'], ARRAY['Executive', 'Strategy', 'Leadership'], 'Executive Director', 'National Economics University', 'Hanoi', 21.0285, 105.8537, true, true, NOW() - INTERVAL '2 hours', NOW() - INTERVAL '9 days'),

-- Users 81-89 (final 9 to reach 98 total with the original user)
(gen_random_uuid(), 'Thủy Phương', 22, 'female', 'male', 'TikTok creator 🎥 Fun & engaging content daily', 'https://api.dicebear.com/7.x/lorelei/svg?seed=thuy1&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1494790108377-be9c29b29330'], ARRAY['Content', 'Social Media', 'Creativity'], 'Content Creator', 'Saigon University', 'Ho Chi Minh', 10.8141, 106.6927, true, true, NOW() - INTERVAL '1 hour', NOW() - INTERVAL '8 days'),
(gen_random_uuid(), 'Nhật Anh', 23, 'female', 'male', 'Pilates instructor 💪 Fitness & wellness coach', 'https://api.dicebear.com/7.x/lorelei/svg?seed=nhat1&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1506435773649-6e0eb8cfb237'], ARRAY['Fitness', 'Wellness', 'Health'], 'Pilates Instructor', 'Far Eastern University', 'Ho Chi Minh', 10.8141, 106.6927, true, false, NOW() - INTERVAL '9 hours', NOW() - INTERVAL '21 days'),
(gen_random_uuid(), 'Lệ Xuân', 25, 'female', 'male', 'Museum curator 🖼️ Art & culture enthusiast', 'https://api.dicebear.com/7.x/lorelei/svg?seed=le1&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d'], ARRAY['Art', 'Culture', 'Museum'], 'Museum Curator', 'Hanoi National University', 'Hanoi', 21.0285, 105.8537, true, true, NOW() - INTERVAL '5 hours', NOW() - INTERVAL '26 days'),
(gen_random_uuid(), 'Thảo Duy', 24, 'female', 'male', 'Brand strategist 📊 Creative & analytical minds', 'https://api.dicebear.com/7.x/lorelei/svg?seed=thao1&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1494790108377-be9c29b29330'], ARRAY['Branding', 'Strategy', 'Marketing'], 'Brand Strategist', 'Hanoi Open University', 'Hanoi', 21.0285, 105.8537, true, false, NOW() - INTERVAL '8 hours', NOW() - INTERVAL '12 days'),
(gen_random_uuid(), 'Kỳ Anh', 26, 'female', 'male', 'Pediatrician 👶 Child healthcare specialist', 'https://api.dicebear.com/7.x/lorelei/svg?seed=ky1&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d'], ARRAY['Healthcare', 'Pediatrics', 'Wellness'], 'Pediatrician', 'Hanoi Medical University', 'Hanoi', 21.0285, 105.8537, true, true, NOW() - INTERVAL '3 hours', NOW() - INTERVAL '17 days'),
(gen_random_uuid(), 'Hạnh Bùi', 23, 'female', 'male', 'Wildlife photographer 🦁 Nature & adventure lover', 'https://api.dicebear.com/7.x/lorelei/svg?seed=hanh2&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1494790108377-be9c29b29330'], ARRAY['Photography', 'Wildlife', 'Travel'], 'Wildlife Photographer', 'Saigon University', 'Ho Chi Minh', 10.8141, 106.6927, true, false, NOW() - INTERVAL '10 hours', NOW() - INTERVAL '23 days'),
(gen_random_uuid(), 'Linh Chi', 24, 'female', 'male', 'Acoustic engineer 🎼 Sound & music technology', 'https://api.dicebear.com/7.x/lorelei/svg?seed=linh4&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d'], ARRAY['Music', 'Technology', 'Audio'], 'Acoustic Engineer', 'BKHN', 'Ho Chi Minh', 10.8141, 106.6927, true, true, NOW() - INTERVAL '4 hours', NOW() - INTERVAL '19 days'),
(gen_random_uuid(), 'Hương Giang', 25, 'female', 'male', 'Corporate trainer 📚 Development & training expert', 'https://api.dicebear.com/7.x/lorelei/svg?seed=huong3&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1494790108377-be9c29b29330'], ARRAY['Training', 'Development', 'Education'], 'Corporate Trainer', 'National Economics University', 'Hanoi', 21.0285, 105.8537, true, false, NOW() - INTERVAL '7 hours', NOW() - INTERVAL '11 days'),
(gen_random_uuid(), 'Ngọc Hân', 26, 'female', 'male', 'Risk management officer ⚠️ Strategic thinker', 'https://api.dicebear.com/7.x/lorelei/svg?seed=ngoc1&backgroundColor=ffd5dc', ARRAY['https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d'], ARRAY['Risk', 'Finance', 'Management'], 'Risk Manager', 'FTU', 'Ho Chi Minh', 10.8141, 106.6927, true, true, NOW() - INTERVAL '6 hours', NOW() - INTERVAL '30 days');

-- Summary: Added 98 new users
-- Total profiles in database will be + 98
-- Dates are realistic (created between 5-30 days ago)
-- Last active varies from 30 minutes to 12 hours ago
-- Mix of both Ho Chi Minh and Hanoi locations
-- Realistic occupations and interests
